spring:
  thymeleaf:
    mode: HTML5
logging:
  level:
    org:
      springframework: error
server:
  port: ${PORT:5000}

wechat:
  appid: ${WECHAT_APPID}
  secret: ${WECHAT_SECRET}

#db:
#  url: ${JDBC_DATABASE_URL:jdbc:postgresql://ec2-50-17-203-51.compute-1.amazonaws.com:5432/d7u9s55dhv0te}
#  username: ${JDBC_DATABASE_USERNAME:hmwxwqwnfqeiso}
#  password: ${JDBC_DATABASE_PASSWORD:6fb17e99198e978bb3d116fcf18cfc7fafc039a62f263a29db4ddd1baa2dbd61}
#  driver: org.postgresql.Driver