spring:
  thymeleaf:
    mode: HTML5
logging:
  level:
    org:
      springframework: error
server:
  port: ${port:8888}
wechat:
  appid: wx0c3aa6eafda7159a
  secret: c5a7d095ab675343cb36af86700b04d7
