spring:
  thymeleaf:
    mode: HTML5
logging:
  level:
    org:
      springframework: error
server:
  port: ${PORT:5000}

wechat:
  appid: ${WECHAT_APPID}
  secret: ${WECHAT_SECRET}

db:
  url: ${JDBC_DATABASE_URL:jdbc:mysql://localhost:3306/jjuask}&useSSL=false&characterEncoding=UTF-8
  username: ${JDBC_DATABASE_USERNAME:root}
  password: ${JDBC_DATABASE_PASSWORD:153182}
  driver: com.mysql.jdbc.Driver